# Generated by Django 3.2.8 on 2021-11-05 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=100, unique=True)),
                ('courseid', models.CharField(max_length=100)),
                ('taskid', models.CharField(max_length=100)),
                ('grade', models.DecimalField(decimal_places=1, max_digits=5)),
                ('result', models.CharField(max_length=50)),
                ('submitted_on', models.DateTimeField()),
                ('source_code', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('extension', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_ratio', models.DecimalField(decimal_places=20, max_digits=28)),
                ('cyclomatic_complexity', models.IntegerField()),
                ('fanout_external', models.IntegerField()),
                ('fanout_internal', models.IntegerField()),
                ('halstead_bugprop', models.DecimalField(decimal_places=20, max_digits=28)),
                ('halstead_difficulty', models.DecimalField(decimal_places=20, max_digits=28)),
                ('halstead_effort', models.DecimalField(decimal_places=20, max_digits=28)),
                ('halstead_timerequired', models.DecimalField(decimal_places=20, max_digits=28)),
                ('halstead_volume', models.DecimalField(decimal_places=20, max_digits=28)),
                ('loc', models.IntegerField()),
                ('maintainability_index', models.DecimalField(decimal_places=20, max_digits=28)),
                ('operands_sum', models.IntegerField()),
                ('operands_uniq', models.IntegerField()),
                ('operators_sum', models.IntegerField()),
                ('operators_uniq', models.IntegerField()),
                ('pylint', models.DecimalField(decimal_places=20, max_digits=28)),
                ('tiobe', models.DecimalField(decimal_places=20, max_digits=28)),
                ('tiobe_compiler', models.DecimalField(decimal_places=20, max_digits=28)),
                ('tiobe_complexity', models.DecimalField(decimal_places=20, max_digits=28)),
                ('tiobe_coverage', models.DecimalField(decimal_places=20, max_digits=28)),
                ('tiobe_duplication', models.DecimalField(decimal_places=20, max_digits=28)),
                ('tiobe_fanout', models.DecimalField(decimal_places=20, max_digits=28)),
                ('tiobe_functional', models.DecimalField(decimal_places=20, max_digits=28)),
                ('tiobe_security', models.DecimalField(decimal_places=20, max_digits=28)),
                ('tiobe_standard', models.DecimalField(decimal_places=20, max_digits=28)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.language')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputs.input')),
            ],
        ),
    ]
