# Generated by Django 3.2.8 on 2021-11-05 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        ('files', '0001_initial'),
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.resource'),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.professor'),
        ),
    ]
