# Generated by Django 3.2.8 on 2021-11-05 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.CharField(max_length=200)),
                ('image2', models.CharField(max_length=200)),
                ('image3', models.CharField(max_length=200)),
                ('image4', models.CharField(max_length=200)),
                ('image5', models.CharField(max_length=200)),
                ('image6', models.CharField(max_length=200)),
                ('csvFile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.csvfile')),
            ],
        ),
    ]
